name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'tests/**'
  pull_request:
    branches: [main, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TestTemplate:

    runs-on: ubuntu-latest

    steps:
      - uses: tercen/actions/start-tercen@main
      - name: docker login
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Install Template Runner
        run: docker pull tercen/workflow_runner:latest
      - name: Test template 
        id: run_test
        run: |
          docker run -t --net=host tercen/workflow_runner:latest \
            --templateRepo=${GITHUB_REPOSITORY} \
            --templateFolder=workflow_tests \
            --user=test \
            --passw=test \
            --opMem="1500000000" \
            --serviceUri=http://127.0.0.1:5400 \
            --gitToken=${{ github.token }} 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: test_results.json
          retention-days: 1